dist: trusty
language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
#install:
#  - pip install -r bot.requirements.txt
#script:
#  - pip install coverage
#  - coverage run caminhoarquivoteste.py test -v 2 --exclude-tag=selenium
after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
# for codecoverage on codeclimate.com
env:
  global:
    - CC_TEST_REPORTER_ID=38209673480d024ecef218e64b24da89a39c51ece937266d308f5493fc25bcf8
# command to run tests